oduwsdl/tmvis

package.json
public/scripts/timeline.js
tmvis.js
watermarkimage.js

Code this branch has deals with multi-channel SSE and works fine in local

SSE optimization

---

hammingdistance.js
lib/mementoFramework.js
public/scripts/timeline.js
simhashOnHTMLContent.js
tmvis.js

Got a tab for Logs, Resolved the refresh issue

Final fixes incorporated 

---

public/index.html

Disabled log tab

---

public/index.html
public/scripts/timeline.js
tmvis.js

solving the case for this sample UIR http://wayback.archive-it.org/2358/20140607131239id_/http://www.hamdeensabahy.com/

Fix for weird case memento returning Blank page and the status is still 200 

---

public/index.html
public/scripts/gif.js
public/scripts/timeline.js
public/styles/sitestyle.css

-Resized GIF to match the size of the slider tab.
-Added download GIF button.
-Added timestamp option. This is an option to have a watermark of the appropriate timestamp on the individual images.
-Got rid of the imagesData array in gif.js because imagesData_IG in imageGridScript.js has the same data and its global so there's no need for imagesData.

Updates on GIF tab

---

public/index.html
public/scripts/histogram.js
public/scripts/timeline.js
public/styles/histogram_style.css
public/styles/sitestyle.css

Added tool tip to histogram.js.
Added tool tip styling to histogram_style.css.

Histogram tool tips

---

Dockerfile

node version fix

---

public/index.html
public/scripts/timeline.js
public/styles/sitestyle.css

- Added memento URI-M download button to summary page
- Modified "Revert" button function to increase load time
- Updated "X" button styling on the image grid tab

New download button

---

public/index.html
public/scripts/timeline.js
public/styles/sitestyle.css
tmvis.js

- Fixed Firefox issue
- Changed histogram page layout
- Added stats page functionality for date range
- Changed date range input format
- Removed unnecessary cache file creation for histogram page
- Refactored back end
- Fixed histogram page not fully loading

New changes and bug fixes

---

public/index.html
tmvis.js

URI-TM working. A wrong path was being requested from the host which led to this feature being unavailable.

URI-TM fixed

---

public/index.html
public/scripts/timeline.js
tmvis.js

- Site now works on older versions of Chrome and Firefox
- Also added another fix for the histogram page occasionally not fully loading

Fix for older browsers

---

README.md
public/index.html
public/scripts/timeline.js
public/styles/sitestyle.css
tmvis.js

- Added interactive brush to select daterange on histogram page
- Added multiple URI support
- Fixed bug that occasionally interfered with summary page load
- Fixed explanation on stats page
- Fixed date range bug that loaded partial timemap after date range stats page
- Fixed caching issue that deleted cache after generating a full timemap
- Changed Help icon

Added features and bug fixes

---

README.md
package.json
public/index.html
public/scripts/histogram.js
public/scripts/imageGridScript.js
public/scripts/timeline.js
public/styles/histogram_style.css
public/styles/sitestyle.css
tmvis.js

- The user gets an option for a particular screenshot to be retaken in the summary page from the image grid.
- New cache system implemented. This new system sends date range information from the cache instead of fetching the timemap again from the archive. Also, if the user requests a date range for a URI that is not cached, after responding to that request, a silent process of calculating the simhash of the full timemap is executed then stored to the cache.
- Zoomable histogram added to the histogram page.
- Added support to handle redirected pages from archives.
- Updated ReadMe file to reflect new changes.
- Added appropriate error messages for date range input.

Added features

---

public/index.html
public/scripts/gif.js
public/scripts/histogram.js
public/scripts/imageGridScript.js
public/scripts/timeline.js
tmvis.js

- When a user enters more than one URI separated by a comma, the GIF has the option of watermarking each image with its associated URI.
- The user may also choose to watermark the images with the URI and timestamp together.
- Additionally, the image grid displays the URI underneath the datetime so that the user knows which of their input URIs that specific memento came from.

URI stamp for multiple URI input.

---

public/scripts/histogram.js
public/scripts/timeline.js
tmvis.js

* Histogram page fetches from the archive all the time to have latest mementos.
* Front-end requests an expected number of mementos which is compared to the number of cached.
* If the expected number matches with the cached number, carry on with the async series in processWithFileContents().
* If not, call updateCache(). This sequence of this function is as follows:
- Fetch timemap from archive
- Filter out cached mementos
- Calculate a simhash on the non-cached mementos
- Merge the non-cached with cached
- Save this timemap to cache
- Call appropriate functions based on the requested role

Changes to caching process

---

README.md
public/index.html
public/scripts/histogram.js
public/scripts/imageGridScript.js
public/scripts/imageSliderScript.js
public/scripts/timeline.js
tmvis.js

- Fixed tabbing and formatting inconsistencies in all files.
- Added documentation
- Simplified some code sections
- Updated README file
- Added functionality to check if cache file contents match the current mementos in the archive
- Reworked histogram to work with a new response format
- Moved memento filtering into function

Added documentation and formatting and code fixes.

---

public/index.html

Users can click the title or its background to jump back to the homepage

Added link to homepage

---

README.md

Used solution provided in #73 
Fixes #73

Updated Docker Development mode documentation

---

README.md
public/index.html
public/scripts/embedded.js
public/scripts/histogram.js
public/scripts/imageSliderScript.js
public/scripts/timeline.js
public/styles/sitestyle.css
tmvis.js

- Date formatting updated to support Firefox and Safari
- Changed Image Slider Play/Pause functions to Prev/Next
- Updated Running Locally and example URIs documentation
- Updated embed code generator

Browser Compatibility Bug Fix

---

public/index.html
public/scripts/histogram.js

- Added link to GitHub repository on the footer
- Message saying "Of the selected mementos, up to 1000 will be analyzed" disappears when less than 1000 mementos are currently selected, and reappears when the user selects over 1000 mementos.

UI Updates

---

public/index.html

- Added link to intro blog post
- Moved ODU logo to right side of footer
- Updated Github repository text
- Moved Twitter link

Formatted footer contents, added link to blog post.
